### ISSUE TITLE
Error in running command for creation of cluster

### ISSUE THREAD

**Issue by Jvanderholst** [Gordonby/AKS-K8S-Lab-L200#5]
During creation of the cluster I receive the following error:
az aks create: error: argument --kubernetes-version/-k: expected one argument

**Comment by Gordonby** [comment]
Yeah, it looks like the az aks get-versions command is returning some versions with a "(preview)" suffix.  This suffix is then subsequently rejected by the az aks create command.

I'm going to remove the specific versioning, as the default now is latest-1.
